version: '3.3'
services:
  testing-server:
    container_name: testing-server
    image: testing-server
    build: 
      dockerfile: Dockerfile
      context: .   
    volumes:
      - /test:/target  
    depends_on: 
      - ozap  

  ozap:
    container_name: zap
    image: owasp/zap2docker-bare:2.7.0
    command: zap.sh -daemon -port 8081 -host 0.0.0.0
    expose:
      # ZAP is running on 8090, we want it to be accessible by our tools        
      - "8081"
      
        
    